### ISSUE TITLE
Timeline For laravel role and permission 

### ISSUE THREAD

**Issue by CHToo** [Metabuyer/laravel-permission-mongodb#10]

**Comment by denielaa** [comment]
[https://app.zenhub.com/files/134222282/958f1c9f-ed0e-41e8-a005-6977e58dc77a/download](https://app.zenhub.com/files/134222282/958f1c9f-ed0e-41e8-a005-6977e58dc77a/download)

@CHToo @StevenTongjl here is timeline for Roles and Permissions

**Comment by khaled-saiful-islam** [comment]
[Role Assignment Timeline_v1.0.1.docx](https://github.com/Metabuyer/laravel-permission-mongodb/files/2131727/Role.Assignment.Timeline_v1.0.1.docx)
