### ISSUE TITLE
Check existing middleware to make sure it works with the new structure

### ISSUE THREAD

**Issue by denielaa** [Metabuyer/laravel-permission-mongodb#21]
The database structure has been change. Need to check all the built in middleware from the library and make fixes if necessary

**Comment by khaled-saiful-islam** [comment]
I have checked existing middleware of permission package. In this package, there are two middleware,
1. PermissionMiddleware (looks okay, we can use it)
2. RoleMiddleware (need to modify one function)

We need to modify the function called "hasAnyRole" for user.
